export default StalksClient;
import StalksClient from "./structures/StalksClient.d.ts";
import Passport from "./structures/accounts/passport/Passport.d.ts";
import Profile from "./structures/accounts/profile/Profile.d.ts";
import Accounts from "./structures/accounts/Accounts.d.ts";
import Advice from "./structures/stalks/weeks/Advice.d.ts";
import Buy from "./structures/stalks/weeks/Buy.d.ts";
import FriendWeek from "./structures/stalks/weeks/FriendWeek.d.ts";
import Prediction from "./structures/stalks/weeks/Prediction.d.ts";
import Sell from "./structures/stalks/weeks/Sell.d.ts";
import Week from "./structures/stalks/weeks/Week.d.ts";
import WeekVersionError from "./structures/stalks/weeks/WeekVersionError.d.ts";
import Stalks from "./structures/stalks/Stalks.d.ts";
import StalksHTTPError from "./structures/StalksHTTPError.d.ts";
export { StalksClient, Passport, Profile, Accounts, Advice, Buy, FriendWeek, Prediction, Sell, Week, WeekVersionError, Stalks, StalksHTTPError };
